---
title: "Temperature and Freshwater as Methods for Controlling D. Vexillum Biofouling"
author: "Payton Arthur, Haze de Haas, Lauren Gill"
date: "27/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract
Paste abstract in here

## Contents
Put in table of contents here

## Libraries

```{r setup, echo=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
library(ggplot2)
library(here)
```

### Reading in Data

```{r}
tunidata <- read.csv("tunicate_master.csv")
```


### Mold Cover

Displaying the data as a proportion of overall score with given mold cover scores
```{r}
tuni_stacked = tunidata %>%
  group_by(mold_cover, temperature_c, water_type) %>%
  summarise(frequency = n())%>%
  mutate(temperature_c=  as.factor(temperature_c))
```

Stacked bar graphs showing mold cover
```{r}
ggplot(tuni_stacked, aes(y = frequency, x = temperature_c, fill = as.factor(mold_cover))) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(. ~ water_type) +
  labs(x ="Temperature (°C)", y = "Frequency")+
  scale_fill_brewer(palette = "Oranges", direction=1) +
  labs(fill = "Mold Cover") +
  theme_cowplot()
```

this is hazel testing my branch
```{r}
#very important code
```
=======
YUHHHHHHHHHHH

Change in Weight over 3 Weeks (compare to post-acclimation)
```{r}
tuni_data1 <- tuni_data %>% mutate(ChangeWetWeight = final_weight_g-post_acclimation_weight_g)

#faceting - put temperature, exposure time and water type on figure

p <- ggplot(tuni_data1, aes(x = exposure_time_s, y = ChangeWetWeight, fill = water_type))+
  labs(x = "Exposure time (s)", y = "Change in wet weight (g)", fill = "Water type")+
#labs(title = "Temperature (°C)")+
  geom_boxplot()

p + facet_grid(cols = vars(temperature_c))

#plot comparing initial wet weight to 3 week wet weight - multiple plots with patchwork?


p1 <- ggplot(tuni_data1, aes(x = exposure_time_s, y = post_acclimation_weight_g, fill = water_type))+
  labs(x = "Exposure time", y = "initial wet weight (g)", fill = "Water type")+
  geom_boxplot()
  
p11 <- p1 + facet_grid(cols = vars(temperature_c))
  
p2 <- ggplot(tuni_data1, aes(x = exposure_time_s, y = final_weight_g, fill = water_type))+
  labs(x = "Exposure time", y = "final weight weight (g)", fill = "Water type")+
  geom_boxplot()

p22 <- p2 + facet_grid(cols = vars(temperature_c))

p11 + p22

p11 + p22 + plot_layout(ncol=1)


hist(tuni_data1$ChangeWetWeight)
shapiro.test(tuni_data1$ChangeWetWeight)
#p-value = 0.7646 thus follows a normal distribution!
descdist(tuni_data1$ChangeWetWeight)


##Does fitdist work on a distribution with negative numbers?
fitDist(ChangeWetWeight, data = tuni_data1, type = "realline", try.gamlss = T)


mod_changeweight <- lm(ChangeWetWeight ~ exposure_time_s + water_type + temperature_c + exposure_time_s*water_type*temperature_c, family = gaussian, data = tuni_data1)
summary(mod_changeweight)

step.mod_changeweight <- stepAIC(mod_changeweight, direction = "backward", trace = F)
summary(step.mod_changeweight)
formula(step.mod_changeweight)

#ChangeWetWeight ~ water_type + temperature_c + water_type:temperature_c

mod_changeweightv2 <- lm(ChangeWetWeight ~ water_type + temperature_c, family = gaussian, data = tuni_data1)
summary(mod_changeweightv2)

#significant p-value for temperature_c90 (p=value = 0.0315)

check_model(mod_changeweightv2)

#check model when water_type:temperature_c was present and had major collinearity issues, thus removed water_type:temperature and check model again and collinearity issues were solved

```

